# Generated by Django 2.0.1 on 2018-10-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('px', '培训机构'), ('gx', '高校'), ('gr', '个人')], default='px', max_length=20, verbose_name='机构类别'),
        ),
    ]
