# Generated by Django 2.0.1 on 2018-10-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20181012_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='/media/text.mp4', max_length=200, verbose_name='访问地址'),
        ),
    ]
