# Generated by Django 2.0.1 on 2018-10-16 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20181012_2314'),
        ('courses', '0005_auto_20181013_1116'),
    ]

    operations = [
    ]
