# Generated by Django 2.0.1 on 2018-10-16 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181013_1319'),
        ('users', '0002_auto_20181012_2314'),
    ]

    operations = [
    ]
